version: '3.8'

services:
  postgres:
    container_name: ${DB_HOST}
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  site:
    container_name: kodex
    image: kodex
    environment:
        - APP_PORT=${APP_PORT}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DB_HOST=${DB_HOST}
        - DB_PASS=${DB_PASS}
        - DB_USER=${DB_USER}
        - SECRET_KEY=${SECRET_KEY}
    ports:
      - ${APP_PORT}:${APP_PORT}
    build:
        context: .
        dockerfile: Dockerfile

    links:
        - postgres
    restart: always
    depends_on:
        - postgres